title: Algemene paginastructuur
hero_image: images/banner.png
description: Hoe de algemene paginastructuur in HTML werkt.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Algemene paginastructuur
