title: Overall page structure
hero_image: images/banner.png
description: How the overall page structure works in HTML.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Overall page structure
