title: Structure globale de la page
hero_image: images/banner.png
description: Comment fonctionne la structure globale de la page en HTML.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Structure globale de la page
